### ISSUE TITLE
Re-enable govulncheck in ci

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#1023]
in #1021, we disabled govulncheck due to the code being identical to upstream, there being many errors, and that PR already being very large. We should fix the vulnerabilities and re-enable the ci checks.

**Comment by rootulp** [comment]
## Notes

- cometbft's main still has vulncheck in the Makefile [here](https://github.com/cometbft/cometbft/blob/bd3acaa455751eb7029380fd1e764747e860dc29/Makefile#L236-L238)
- cometbft's main is passing vulncheck in CI [here](https://github.com/cometbft/cometbft/actions/runs/6576224249)

**Comment by rootulp** [comment]
Confirmed all vulnerabilities go away after bumping to Go 1.21.3:

```
$ make vulncheck
Scanning your code and 582 packages across 95 dependent modules for known vulnerabilities...

=== Informational ===

Found 1 vulnerability in packages that you import, but there are no call
stacks leading to the use of this vulnerability. You may not need to
take any action. See https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
for details.

Vulnerability #1: GO-2023-2102
    HTTP/2 rapid reset can cause excessive work in net/http
  More info: https://pkg.go.dev/vuln/GO-2023-2102
  Module: golang.org/x/net
    Found in: golang.org/x/net@v0.7.0
    Fixed in: golang.org/x/net@v0.17.0

No vulnerabilities found.

Share feedback at https://go.dev/s/govulncheck-feedback.
```
