### ISSUE TITLE
Show celestia version in the RPC status endpoint

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-core#1035]
We need some way of working out which version of Celestia users are using. Currently, `/status` returns a version but it is the version of Tendermint.

**Proposal**

Take the `Version` field returned in the `Info` ABCI call and plumb it into the node info that gets displayed in the `/status` endpoint (as well as in the p2p handshake)

**Comment by rootulp** [comment]
[Question] why does the celestia-app version need to be propagated in the `/status` endpoint? Are the `/abci_info` or `/node_info` endpoints not sufficient?
