### ISSUE TITLE
`total_voting_power` missing from RPC response

### ISSUE THREAD

**Issue by ratankaliani** [celestiaorg/celestia-core#1052]
## Bug Report
While querying several Celestia testnet RPC's for the most recent `signed_block`, they fail to include `total_voting_power` within the `ValidatorSet` struct.

`total_voting_power` should be included in congruence with the [protobuf specification for `ValidatorSet`](https://github.com/celestiaorg/celestia-core/blob/main/proto/tendermint/types/validator.proto#L9-L13) which is one of the fields in [`ResultSignedBlock`](https://github.com/celestiaorg/celestia-core/blob/main/rpc/core/types/responses.go#L45-L50).

### Setup

Queried several RPC's for `signed_block`

[NodesGuru](https://rpc-2.celestia.nodes.guru/signed_block)
[Nodestake](https://rpc-t.celestia.nodestake.top/signed_block)

### What happened?

Missing `total_voting_power` from `signed_block` RPC response

### What did you expect to happen?

`total_voting_power` that matches the sum of of all of the validators' voting power should be included in the RPC reponse inside of the `validator_set` struct.

### How to reproduce it

Query Celestia testnet RPC's for the most recent `signed_block` and verify if `total_voting_power` is returned.

### Anything else we need to know

The lack of this field means that Rust developers need to create a mirror struct that has an optional `total_voting_power`, as they can't use `Set` from `tendermint-rs`: https://github.com/informalsystems/tendermint-rs/blob/c2b5c9e01eab1c740598aa14375a7453f3bfa436/tendermint/src/validator.rs#L20-L24

If this is an intentional design decision to not return `total_voting_power` for signed blocks, a PR can be made to `tendermint-rs` to update the `total_voting_power` field of `Set` to be optional.

**Comment by rootulp** [comment]
I don't think it's an intentional decision from Celestia to remove `total_voting_power` from this response. I think it's not in the RPC response b/c it's not an exported field https://github.com/celestiaorg/celestia-core/blob/d02553fdba2720f0314f2f6451a5d50b6755e62c/types/validator_set.go#L56-L57

I verified that it's still un-exported in upstream CometBFT [here](https://github.com/cometbft/cometbft/blob/c3acdb866f885e94dcd0e1ef8ecce53ff689216c/types/validator_set.go#L56-L57).

**Comment by rootulp** [comment]
Based on https://github.com/cometbft/cometbft/issues/1178 it seems unlikely that upstream will export the field anytime soon so we may want to go with the alternative option you suggested:

> If this is an intentional design decision to not return total_voting_power for signed blocks, a PR can be made to tendermint-rs to update the total_voting_power field of Set to be optional.

**Comment by ratankaliani** [comment]
Sounds good - thanks for opening the fix!
