### ISSUE TITLE
Add further standard tracing

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#1056]
We're adding a few optional tracing points in #1055, but to continue #978, we should add an additional standard table that traces the local state of the mempool, consensus peer state (such as when our peers are getting new valid blocks, votes, peer disconnections, gossiping related to the pex, local address book state, and perhaps more.

Originally posted https://github.com/celestiaorg/celestia-core/pull/1055#discussion_r1285957603

**Comment by staheri14** [comment]
Created a [Notion page](https://www.notion.so/celestiaorg/Effect-of-spamming-on-network-performance-ca7d3100989b483cbdaff16670b2f216) exclusively aimed at compiling insights and discoveries pertaining to the performance evaluation of the network under a spamming attack. This encompasses the testing scenario, essential metrics, and performance indicators.

**Comment by evan-forbes** [comment]
standard tracing was added, so I'm going to close this for now.
