### ISSUE TITLE
Consider pruning the tx index

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#1065]
Transaction indexes can be useful for looking up recent transactions, at the cost of duplicating storage. We do not currently have a way of pruning the tx index storage. Naively, it seems likely that we could prune the tx index as we prune blocks.

If we decide to work on this issue, we should try to upstream this work.

**Comment by Yh010** [comment]
1)http://www.diva-portal.org/smash/get/diva2:1275025/FULLTEXT02.pdf
Useful resource probably

**Comment by evan-forbes** [comment]
closing in favor of #1163
