### ISSUE TITLE
Consider adding the ability to prune the tx index

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#1070]
We've gone back and forth on the default tx index value in the config.toml, and now we're going back to using "null" in https://github.com/celestiaorg/celestia-app/issues/2322. One of the main reasons not to enable this is because there currently is no pruning for the txindex, so the amount of block data stored is **double** what it would be if we didn't prune block data.

Another alternative would be to only store the txs once in the index, and then store hashes in the block data. 

We should probably wait until "the merge", before making any dramatic changes to how comet handles block data give our plan is store block data once in the share format used in the square encoding.

**Comment by cmwaters** [comment]
I think we should just implement a secondary index for the transaction hash so that users can work out whether their transaction has been committed or not (right now this is not possible).

**Comment by cmwaters** [comment]
This is possible duplicated here: https://github.com/celestiaorg/celestia-core/issues/1065

**Comment by evan-forbes** [comment]
closing in favor of https://github.com/celestiaorg/celestia-core/issues/1163
