### ISSUE TITLE
Enhancing Prometheus metrics for BW consumption

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-core#1077]
As part of https://github.com/celestiaorg/celestia-app/issues/2197, in order to be able to calculate the breakdown of BW consumption per chain ID and reactor, we would like to use to the existing Prometheus metrics in cekestia-core. However, it is not clear whether the current metrics are sufficient and whether we may require additional metrics to accomplish the task. 
This issue intends to track the progress of this effort.

**Comment by staheri14** [comment]
Currently, Prometheus collects the[ sent and received BW](https://github.com/celestiaorg/celestia-core/blob/9e02fe1e7bee8105eea8f69b0a6d0825dd9552a7/p2p/metrics.go#L41-L43), however, they lack two major labels: Channel id and the reactor. So we need to integrate these two.

**Comment by staheri14** [comment]
In the existing implementation, there is a single reactor associated with each channel ID. Therefore, we can deduce the reactors based solely on the channel ID label. Given this, our approach will involve appending only the channel ID label to each metric.
References: 
https://github.com/celestiaorg/celestia-core/blob/2f93fc823f17c36c7090f84694880c85d3244764/node/node.go#L633-L637 
https://github.com/celestiaorg/celestia-core/blob/2f93fc823f17c36c7090f84694880c85d3244764/node/node.go#L690
https://github.com/celestiaorg/celestia-core/blob/2f93fc823f17c36c7090f84694880c85d3244764/node/node.go#L153-L158

**Comment by rootulp** [comment]
> In the existing implementation, there is a single reactor associated with each channel ID.

Is this guaranteed for future modifications to CometBFT? Is there a downside to including two labels?

**Comment by staheri14** [comment]
> Is this guaranteed for future modifications to CometBFT?  

The 1:1 correspondence between reactors and channel IDs is not strictly enforced by the current implementation, as custom reactors can be added to switches on any channel ID. However, it is probable, based on past trends, that the one-to-one mapping will continue to be maintained in the future (although not guaranteed with 100% certainty).

> Is there a downside to including two labels?

Thank you for your suggestion. Our current implementation, which tracks channel ID, adequately addresses the requirements of this issue. Adding an extra label could introduce redundancy and complexity without a significant improvement in observability.
Our initial goal was to minimize modifications to the existing Prometheus metrics. Currently, we monitor sent and received bytes at the peer level, the central point of communication with peers. Extending this observability to specific reactors would require changes at higher levels, increasing the scope significantly. The reason is that in the peer level there is no observability into the reactors to which/from which the message sent. Identifying the exact reactor needs to be done in higher level components, and the surface would much larger. 

While enhancing observability by identifying reactors is possible,  the current approach was opted to maintain simplicity and efficiency while meeting the objectives of this issue.

**Comment by staheri14** [comment]
apparently, no two reactors can share the same channel ID as suggested in https://github.com/celestiaorg/celestia-core/blob/3f3b7cc57f5cfc5e846ce781a9a407920e54fb72/p2p/switch.go#L166

**Comment by evan-forbes** [comment]
if I recall correctly, I've been able to determine the bandwidth used before via channel ID, but would have to dig through the metrics. Will hopefully be able to do that later today depending on if I can get the network tests working again

**Comment by staheri14** [comment]
> if I recall correctly, I've been able to determine the bandwidth used before via channel ID, but would have to dig through the metrics. Will hopefully be able to do that later today depending on if I can get the network tests working again

[Reiterating the findings from our discussion in #1078], it has been clarified that the metrics in question are `peer_send_bytes_total` and `peer_receive_bytes_total`. Although these metrics include channel IDs, they are presently missing a message type label, rendering them insufficient for providing the desired level of granularity. Nevertheless, the decision reached that we could use them to cross-check results extracted from `message_receive_bytes_total` and `message_send_bytes_total`.

**Comment by staheri14** [comment]
closed by https://github.com/celestiaorg/celestia-core/pull/1091
