### ISSUE TITLE
Patch grpc

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#1127]
per notice 

### Impact
In affected releases of gRPC-Go, it is possible for an attacker to send HTTP/2 requests, cancel them, and send subsequent requests, which is valid by the HTTP/2 protocol, but would cause the gRPC-Go server to launch more concurrent method handlers than the configured maximum stream limit.

### Patches
This vulnerability was addressed by #6703 and has been included in patch releases: 1.56.3, 1.57.1, 1.58.3. It is also included in the latest release, 1.59.0.

Along with applying the patch, users should also ensure they are using the grpc.MaxConcurrentStreams server option to apply a limit to the server's resources used for any single connection.

### Workarounds
None.

### References
[#6703](https://github.com/grpc/grpc-go/pull/6703)

### References
[GHSA-m425-mq94-257g](https://github.com/grpc/grpc-go/security/advisories/GHSA-m425-mq94-257g)
https://github.com/grpc/grpc-go/pull/6703
https://github.com/grpc/grpc-go/commit/f2180b4d5403d2210b30b93098eb7da31c05c721

**Comment by rootulp** [comment]
Seems we are affected

https://github.com/celestiaorg/celestia-core/blob/bdadcefb65519d4d09a143cb3a96809785f1eb40/go.mod#L39

The most recent CometBFT 0.34.x release (0.34.29) also uses v.1.52.0 [here](https://github.com/cometbft/cometbft/blob/fe4894f4482b49c9bfe93382a2409f26c6f3f712/go.mod#L39) so pulling from upstream won't resolve.

We can bump from v.1.52.0 to v.1.59.0 but we should be careful to audit grpc-go [release notes](https://github.com/grpc/grpc-go/releases) to ensure we aren't impacted by a breaking change.

**Comment by evan-forbes** [comment]
we could also bump to 1.56.3 I believe. Not sure exactly sure what value to pick for `grpc.MaxConcurrentStreams`, but I'm assuming we should just be able to pick a pretty high number and not have consequences or the need to congfigure it further

**Comment by evan-forbes** [comment]
also, I'm super ok with just hanlding any breakages here instead of waiting for upstream. Ideally we'd bump upstream and pull here for both the release branch and for main

**Comment by rootulp** [comment]
> Not sure exactly sure what value to pick for `grpc.MaxConcurrentStreams`

Hmm I'll investigate if we can rely on the default of `100`. 

Ref:
- https://github.com/grpc/grpc-go/blob/c76d75f4f95626e9e6c0008e6a6120d43747b519/internal/transport/defaults.go#L34
- https://github.com/grpc/grpc-go/blob/c76d75f4f95626e9e6c0008e6a6120d43747b519/internal/transport/http2_client.go#L343

**Comment by evan-forbes** [comment]
dope, thanks for looking that up!

**Comment by rootulp** [comment]
CometBFT doesn't explicitly set a MaxConcurrentStreams option [here](https://github.com/cometbft/cometbft/blob/22af40641c58f565b6cc694c9e9871a381627309/abci/server/grpc_server.go#L46) but we can set it to `100` to satisfy this recommendation:

> Along with applying the patch, users should also ensure they are using the grpc.MaxConcurrentStreams server option to apply a limit to the server's resources used for any single connection.
