### ISSUE TITLE
Attempting to use CAT in testground fails

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#1140]
When running testground tests that use the v2 mempool, we fail to reach consensus after a few blocks. Its unclear why this occurs atm, but we need to fix this before we can get data on the improvement CAT offers along with feeling confident to try it more broadly on testnets.

**Comment by evan-forbes** [comment]
the exact same test but configured for v1 works as intented. I'm not sure if its a testground thing or not tho

**Comment by evan-forbes** [comment]
can close with https://github.com/celestiaorg/celestia-app/pull/3014

**Comment by rootulp** [comment]
Out of curiosity, what was wrong with CAT pool? How does https://github.com/celestiaorg/celestia-app/pull/3014 fix?

**Comment by evan-forbes** [comment]
I don't think anything is wrong afaict atm, it was just an issue somewhere in testground
