### ISSUE TITLE
Investigating potential duplicate data submission by InfluxDB Client due to network failures

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-core#1146]
Originally discovered and shared at https://github.com/celestiaorg/celestia-core/issues/1138#issuecomment-1843497095, there is a possibility that the InfluxDB client is inadvertently resubmitting duplicate data points as part of its retry mechanism following network failures, leading to duplicate entries.

The purpose of this issue is to explore and confirm this theory, and implement any required changes in the code to address it.

**Comment by evan-forbes** [comment]
is the time different in the duplicate points? If so, then in order for this to occur, the client would have to override the time that is set when writing the point. I don't think this happens, but if it does we definitely need to fix it as it invalidates all of our data

**Comment by staheri14** [comment]
> is the time different in the duplicate points? If so, then in order for this to occur, the client would have to override the time that is set when writing the point. I don't think this happens, but if it does we definitely need to fix it as it invalidates all of our data

The timestamp of duplicate points are different. 
Upon examining the code https://github.com/celestiaorg/celestia-core/blob/4b6c2dda7dfb4cd9c74986a2a4a98d1bab44d961/pkg/trace/client.go#L146 it appears that each data point is timestamped only once. Consequently, if a duplicate data point is retransmitted by the InfluxDB client, it would retain the original timestamp, resulting in identical timestamps for such duplicates.

**Comment by staheri14** [comment]
While this [observation](https://github.com/celestiaorg/celestia-core/issues/1146#issuecomment-1843798204) could potentially cast doubt on the hypothesis of client-side duplications due to network failures, there is still no explanation provided for the presence of duplicate points on the server side, as mentioned in this [comment](https://github.com/celestiaorg/celestia-core/issues/1138#issuecomment-1843745981). I'll continue debugging.

**Comment by staheri14** [comment]
Given that influxDB feature is now/going to be replaced with the local tracing, we can close this issue.
