### ISSUE TITLE
creating a named error from `timed out waiting for tx to be included in a block`

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/celestia-core#1168]
We have an [open issue](https://github.com/celestiaorg/celestia-node/issues/3078) for an error we’re getting from blob submission (`timed out waiting for tx to be included in a block`) which originates from [core](https://github.com/celestiaorg/celestia-core/blob/570aa7ed3b1b309b7c249562a9e034a48ad823f6/rpc/core/mempool.go#L140). We need to be able to detect this for resubmission and I’m wondering if it makes sense to add a named error in app to catch this - otherwise we will do a string match in node itself.

**Comment by rootulp** [comment]
Released https://github.com/celestiaorg/celestia-core/releases/tag/v1.33.0-tm-v0.34.29
