### ISSUE TITLE
Lack of channel ID prioritization in MConnection's message receiving process

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-core#1192]
## Problem
**Summary:** Currently, there is no channel ID prioritization on the receiving side of an [`MConnection`](https://github.com/celestiaorg/celestia-core/blob/34b83b51889c92a9818221bb01dc78a35dc55c77/p2p/conn/connection.go#L78). This results in sequential processing of incoming messages without prioritizing important messages, such as those for voting.

**More context:** In the `MConnection`, sending channels are associated with priorities, which affects the order in which messages are sent. However, on the receiving end, all messages are processed in the order they arrive. For example, if there are 100 messages with a lower priority (i.e., belonging to a channel ID with low priority) in line (i.e., in the` MConnection`'s [`bufConnReader`](https://github.com/celestiaorg/celestia-core/blob/34b83b51889c92a9818221bb01dc78a35dc55c77/p2p/conn/connection.go#L82)), and the 101st message is an important one, the [`recvRoutine`](https://github.com/celestiaorg/celestia-core/blob/34b83b51889c92a9818221bb01dc78a35dc55c77/p2p/conn/connection.go#L560) will only process this important message after completing all the preceding 100 messages. Essentially, there is no priority for channel IDs implemented on the receiving side. This contrasts with the sending side, where even if a low priority channel ID has pending messages, the sending routine [`sendRoutine()`](https://github.com/celestiaorg/celestia-core/blob/34b83b51889c92a9818221bb01dc78a35dc55c77/p2p/conn/connection.go#L422) will prioritize a message from a higher priority channel ID over them and send it earlier ([these lines](https://github.com/celestiaorg/celestia-core/blob/34b83b51889c92a9818221bb01dc78a35dc55c77/p2p/conn/connection.go#L525-L538)). To be precise, the priority is determined by the ratio of the amount of recently sent bytes to the channel ID's absolute priority.

## Acceptance Criteria
- [x] Provide a test that demonstrates the sequential receipt of messages in `MConnection`. #1193 
- [x] Implement a mechanism to prioritize processing incoming messages according to their channel ID priority (similar to the sender side).

**Comment by staheri14** [comment]
I believe this issue can be marked as “Done,” as all action items have been addressed. While the final implementation has not been decided for integration into the code, a prototype was completed. I’d suggest closing this issue as done, and if necessary, creating a new issue to advocate for implementing it at the production level if needed. cc: @evan-forbes

**Comment by evan-forbes** [comment]
sgtm
