### ISSUE TITLE
CI Test flake for `TestTxPool_ConcurrentTxs`

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#1194]
we observed a test flake for `TestTxPool_ConcurrentTxs` in https://github.com/celestiaorg/celestia-core/actions/runs/7647773719/job/20839332649#step:6:174

**Comment by evan-forbes** [comment]
same thing here. Before we try CAT out again on a public network, we need to get to the bottom of these

> panic: test timed out after 8m0s
running tests:
	TestTxPool_ConcurrentTxs (7m58s)

goroutine 124 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.22.1/x64/src/testing/testing.go:2366 +0x265
created by time.goFunc
	/opt/hostedtoolcache/go/1.22.1/x64/src/time/sleep.go:177 +0x45

goroutine 1 [chan receive, 7 minutes]:
testing.(*T).Run(0xc000206b60, {0x149f3a8, 0x18}, 0x15b3a00)
	/opt/hostedtoolcache/go/1.22.1/x64/src/testing/testing.go:1750 +0x851
testing.runTests.func1(0xc000206b60)
	/opt/hostedtoolcache/go/1.22.1/x64/src/testing/testing.go:2161 +0x86
testing.tRunner(0xc000206b60, 0xc000053b00)
	/opt/hostedtoolcache/go/1.22.1/x64/src/testing/testing.go:1689 +0x21f
testing.runTests(0xc000[130](https://github.com/celestiaorg/celestia-core/actions/runs/8465703336/job/23192965729?pr=1178#step:6:131)450, {0x1d9f620, 0x27, 0x27}, {0xc000053ba8?, 0xc000053bf0?, 0x1dad500?})
	/opt/hostedtoolcache/go/1.22.1/x64/src/testing/testing.go:2159 +0x8bf
testing.(*M).Run(0xc0003485a0)
	/opt/hostedtoolcache/go/1.22.1/x64/src/testing/testing.go:2027 +0xf18
main.main()
	_testmain.go:159 +0x2e5

goroutine 12 [semacquire, 7 minutes]:
sync.runtime_Semacquire(0xc00019ba88?)
	/opt/hostedtoolcache/go/1.22.1/x64/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc00019ba80)
	/opt/hostedtoolcache/go/1.22.1/x64/src/sync/waitgroup.go:116 +0xa5
github.com/cometbft/cometbft/mempool/cat.TestTxPool_ConcurrentTxs(0xc000207ba0)
	/home/runner/work/celestia-core/celestia-core/mempool/cat/pool_test.go:533 +0x5d3
testing.tRunner(0xc000207ba0, 0x15b3a00)
	/opt/hostedtoolcache/go/1.22.1/x64/src/testing/testing.go:1689 +0x21f
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.22.1/x64/src/testing/testing.go:1742 +0x826

goroutine 14 [chan receive]:
github.com/cometbft/cometbft/mempool/cat.TestTxPool_ConcurrentTxs.func2()
	/home/runner/work/celestia-core/celestia-core/mempool/cat/pool_test.go:501 +0x1be
created by github.com/cometbft/cometbft/mempool/cat.TestTxPool_ConcurrentTxs in goroutine 12
	/home/runner/work/celestia-core/celestia-core/mempool/cat/pool_test.go:494 +0x5c6

**Comment by rootulp** [comment]
Related:

```
panic: test timed out after 8m0s
	running tests:
		TestTxPool_ConcurrentTxs (7m58s)
```

https://github.com/celestiaorg/celestia-core/actions/runs/10965650399/job/30451941597?pr=1495#step:6:126
