### ISSUE TITLE
Add the ability to scrape metrics and pprof data to disk

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#1225]
Testground frequently has issues with metric and pprof collection. While incredibly hacky, if we have the ability to scrape metric and pprof data to disk, then that data can be pushed to an external server. This would allow relying less on the tracer, and would allow us to use the same introspection tools that could be used in an IRL network.

**Comment by staheri14** [comment]
Following our last sync, adding myself to the assignees.

**Comment by evan-forbes** [comment]
closing as unplanned since we have a way to push metrics to a gateway

**Comment by staheri14** [comment]
The second part of this issue has been addressed in the following PR https://github.com/celestiaorg/big-blocks-research/pull/1
