### ISSUE TITLE
Track how many transactions are rejected by the application as a metric

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#1241]
We could track as a metric how many transactions are rejected by the application

_Originally posted by @cmwaters in https://github.com/celestiaorg/celestia-core/issues/1007#issuecomment-1956230419_

**Comment by 0xEclair** [comment]
Why not use metric for failed transactions?

**Comment by rootulp** [comment]
I think this issue was closed by https://github.com/celestiaorg/celestia-core/pull/1445 which merged into v0.34.x-celestia and released as part of https://github.com/celestiaorg/celestia-core/releases/tag/v1.39.0-tm-v0.34.29
