### ISSUE TITLE
Unable to Build celestia-core with Go 1.22 Compiler

### ISSUE THREAD

**Issue by walldiss** [celestiaorg/celestia-core#1243]
Problem:
Attempting to build celestia-core with the Go 1.22 compiler results in failure due to deprecated calls within Pyroscope dependencies.

Error Details:
```
# github.com/pyroscope-io/godeltaprof/internal/pprof
../../go/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.2/internal/pprof/delta_mutex.go:25:20: undefined: runtime_cyclesPerSecond
../../go/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.2/internal/pprof/proto.go:400:8: undefined: runtime_expandFinalInlineFrame
```

Solution:
The issue can be resolved by upgrading to the latest version of Pyroscope.

**Comment by Wondertan** [comment]
Ref/dup of https://github.com/celestiaorg/celestia-node/issues/3178
