### ISSUE TITLE
Fixing/verifying consensus round state traced data

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-core#1258]
Based on the findings reported in issue #1257, discrepancies have been noted in the recorded heights for `RoundStepPropose` and `RoundStepPrevote`. This issue aims to monitor the problem and determine whether the tracing data requires updates.

**Comment by evan-forbes** [comment]
https://github.com/celestiaorg/celestia-core/issues/1257#issuecomment-1986490954

**Comment by staheri14** [comment]
Closing this issue: The discrepancies observed is due to the fact that the timestamp associated with each block height actually reflects the finalization time of the block preceding it.
