### ISSUE TITLE
Modify hashing function if we choose to go with Compact Blocks

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-core#1280]
This serves as more of a reminder. I am not trying to presuppose that we will use compact blocks. However, in the case that we do, it's import that we modify the hash function outlined here:

https://github.com/celestiaorg/celestia-core/blob/e8724248c7d6a438ec08046e82525c83a2d64941/types/tx.go#L32-L40

Or at least modify the hashes used in the cat pool to return the entire hash of the data that is being transmitted. If we don't then someone could modify the contents of a BlobTx and we would not be able to notice that it is a different transaction from the one proposed.

Put another way, the hash over the complete data is needed in compact blocks for the integrity of what is being proposed and eventually committed
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
are we calling checktx on the returned data? if so, are we verifying the blobTx?

and is this only for versions of compact blocks that use the mempool to propogate missing portions of the block in the mempool? ie, in a more breaking version where we change the partsetheader do we have the same issue?

**Comment by cmwaters** [comment]
> are we calling checktx on the returned data? if so, are we verifying the blobTx?

> Yes we are still calling checktx. I wonder the fact that the blob commitments are in the PFB means that someone actually can't modify any of the contents of the blob
