### ISSUE TITLE
Implement a migration script for the breaking config in v0.34.x

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#1299]
> I would still like to understand the release strategy for this breaking change.

this is a good point, and we should document this. in the past, we've briefly discussed using a migration script. In a similar vein to a migration script, if we know what the error is, then we can automatically fix the config and log it should that error occur.

_Originally posted by @evan-forbes in https://github.com/celestiaorg/celestia-core/issues/1290#issuecomment-2051005994_

for more context on this, there is a bug in viper that stops it from properly reading yaml. See #1143 and #1141

**Comment by cmwaters** [comment]
There was an attempt at automatically migrating config files in `CometBFT`. I think the tool was left behind so not sure if it's currently in use at all

**Comment by rootulp** [comment]
A config migration script seems prone to error and IMO warrants a lot of additional testing. We can circumvent that effort by deprecating the current config that is `influxdb` specific and adding new config.

**Comment by evan-forbes** [comment]
closing as this is no longer needed.
