### ISSUE TITLE
Upgrade to CometBFT v0.34.33

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-core#1344]
## Context

v0.34.x-celestia is currently based on v0.34.29 of CometBFT. There have been a few more releases to the v0.34.x line since then.

## Proposal

Upgrade to CometBFT [v0.34.33](https://github.com/cometbft/cometbft/blob/v0.34.33/CHANGELOG.md) on v0.34.x-celestia

**Comment by evan-forbes** [comment]
closing as completed

**Comment by rootulp** [comment]
Confirmed we upgraded to CometBFT v0.34.35 in https://github.com/celestiaorg/celestia-core/pull/1495
