### ISSUE TITLE
Deprecate v0 mempool

### ISSUE THREAD

**Issue by ninabarbakadze** [celestiaorg/celestia-core#1387]
## Description

v0 mempool is currently not enabled but still in the codebase which means that we have to maintain the implementation. 

## Acceptance Criteria

- [ ] Remove v0 mempool from the codebase

**Comment by ninabarbakadze** [comment]
we can delete or close this one @rootulp

**Comment by rootulp** [comment]
Sounds good, let's close this in favor of https://github.com/celestiaorg/celestia-core/issues/1382
