### ISSUE TITLE
Look into fixing duplicate protobuf type registry 

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#145]
lazyledger-core still uses the same package declaration in its proto files as tendermint, which causes some types to be registered more than once when it is imported along with tendermint. This is the case with the cosmos-sdk, which imports tendermint/iavl, and iavl depends on old versions of tendermint. 
```
2021/01/12 11:08:17 proto: duplicate proto type registered: tendermint.crypto.Proof
2021/01/12 11:08:17 proto: duplicate proto type registered: tendermint.crypto.ValueOp
2021/01/12 11:08:17 proto: duplicate proto type registered: tendermint.crypto.DominoOp
2021/01/12 11:08:17 proto: duplicate proto type registered: tendermint.crypto.ProofOp
2021/01/12 11:08:17 proto: duplicate proto type registered: tendermint.crypto.ProofOps
```
We could use different package declarations in lazyledger-core's proto files or, at least for now, could ignore these warnings. Not only will we [replace iavl](https://github.com/lazyledger/cosmos-sdk/issues/6) soon, but the types that are registered twice are identical in ll-core and tendermint, so it doesn't matter which we use.

**Comment by evan-forbes** [comment]
we can close with with merging of [#127](https://github.com/celestiaorg/lazyledger-app/pull/127)

**Comment by marbar3778** [comment]
since this is abck to being a fork, it would be good to change the proto files paths as well. it could help in the long run

**Comment by evan-forbes** [comment]
this was fixed when we changed the path declaration back to tendermint
