### ISSUE TITLE
fix `TestTxMempool_ExpiredTxs_Timestamp` flakes

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#1506]
fix `TestTxMempool_ExpiredTxs_Timestamp` flakes

[adding a comment to create an issue from]

_Originally posted by @evan-forbes in https://github.com/celestiaorg/celestia-core/pull/1495#discussion_r1778759236_

**Comment by rootulp** [comment]
Closing as duplicate of https://github.com/celestiaorg/celestia-core/issues/1502
