### ISSUE TITLE
Pull based catchup

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#1522]
Currently, nodes will send catchup block data if they don't receive state updates from peers. This aggressive catchup routine is very error prone, because state messages are far from instant. Especially when the network is congested and state messages take longer to be received. Not only that, but if the peer is actually behind due to congestion, the congestion will only get worse as all of their peers will each send them block data.

Instead, nodes should request data from specific peers when they notice they are behind.

While slightly more conservative, it should significantly improve congestion.

This is related to the other efforts for faster recovery and compact blocks https://github.com/celestiaorg/celestia-core/issues/1334

**Comment by cmwaters** [comment]
Will this pull-based block part mechanism also replace block propagation or just catchup?

**Comment by evan-forbes** [comment]
closing in favor of https://github.com/celestiaorg/celestia-core/issues/1532
