### ISSUE TITLE
git sync

### ISSUE THREAD

**Issue by marbar3778** [celestiaorg/celestia-core#180]
## Summary

After we have migrated the current merged tendermint version to 0.34.x line I would suggest we use https://github.com/marketplace/actions/github-repo-sync to automatically keep the repo in sync. 

For the merging of 0.34.x into LL there are two options. 

- Manually merging and deleting commits in repo
- Cherry pick the LL changes onto 0.34.x and push that to master. 

Is there a preference?

**Comment by liamsi** [comment]
OK, so git-sync only makes sure that branches here are in sync with upstream. That would be very helpful, e.g. to sync the release branches. This would be cool for all forks we are using (go-ipfs etc).

> Manually merging and deleting commits in repo

I think I'm slightly in favour of this option as it keeps the current history (minus very few commits) in place. But honestly, whatever is simpler to use works.

**Comment by marbar3778** [comment]
Will look at how many LL commits there are. If it's not many I will try my luck 😄

**Comment by liamsi** [comment]
It shouldn't be too crazy. @evan-forbes might appreciate if he could participate in this somehow. Maybe we could do a short pair-programming session for this?

**Comment by liamsi** [comment]
Feel free to reopen if still relevant @evan-forbes.
