### ISSUE TITLE
BlockID: replace with header hash + add/use DA header instead of PartsSetHeader

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-core#184]
## Summary

In Tendermint, the [BlockID](https://github.com/tendermint/tendermint/blob/884d4d525299e4d43ab881ac19062501c1e09ddf/types/block.go#L1172-L1176) is comprised of the `Header` [hash](https://github.com/tendermint/tendermint/blob/884d4d525299e4d43ab881ac19062501c1e09ddf/types/block.go#L448:18) and the [`PartSetHeader`](https://github.com/tendermint/tendermint/blob/884d4d525299e4d43ab881ac19062501c1e09ddf/types/part_set.go#L94-L97). 
In LazyLedger, we do not need the PartSetHeader as we will remove the concept of "parts" with an erasure coded variant (see #163). Hence, the `BlockID` needs to be changed too.

## Problem Definition

The BlockID needs to be simplified into the header's hash as the PartsSetHeader will be replaced with the DA header.

## Proposal

This seemingly simple change will result in a relatively large PR as the BlockID is used a lot, everywhere. Preferably, we should split this up into at least to PRs / self-contained packages. Changing the header hash into a simple hash (instead of as currently merkelizing it) can be done separately. Then, after using the DA header everywhere, we can remove the PartSetHeader together with the PartsSet struct itself. From the perspective of getting LazyLedger ready, switching from merkelizing to a simple hash is mostly a cosmetic change (with low priority), while using the DA header instead of the PartsetHeader (as a single commitment to data) is absolutely required. **Update**: We could actually continue using the PartSetHeader as an implementation details during consensus but we should still remove it from the BlockID (as it would be a second commitment to the block data additional to the DAHeader).

_The work ideally should be split up like this_: https://github.com/lazyledger/lazyledger-core/pull/205#issuecomment-804292134

There are also plans to simplify it in tendermint, too. See for instance:
 - https://github.com/tendermint/spec/issues/78
 - https://github.com/tendermint/spec/issues/199

Also related: 
- https://github.com/lazyledger/lazyledger-specs/blob/master/specs/data_structures.md#header
- https://github.com/lazyledger/lazyledger-specs/blob/master/specs/data_structures.md#availabledataheader

**Comment by evan-forbes** [comment]
can we close this issue as well?

**Comment by liamsi** [comment]
Yeah, let's close for now. If anything let's help make https://github.com/tendermint/spec/issues/78 happen.
