### ISSUE TITLE
Update the test coverage script to lazyledger/lazyledger-core

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#188]
We never got around to updating the test coverage script after forking from tendermint. We should change the `./test/test_cover.sh` script from tendermint/tendermint to lazyledger/lazyledger-core

**Comment by liamsi** [comment]
This is still necessary: https://github.com/celestiaorg/celestia-core/blob/6f335f672566079f1ad8f575079bd47b6cc6f5b9/test/test_cover.sh#L3

**Comment by evan-forbes** [comment]
yeah, I think we can close this

**Comment by liamsi** [comment]
I'm confused. So changing this is _not_ necessary?

**Comment by evan-forbes** [comment]
yeah, it uses the go.mod file, which still uses github.com/tendermint/tendermint, so we shouldn't change it now that we switched backed to a fork
