### ISSUE TITLE
crypto: use ecdsa / secp for consensus message signing

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-core#200]
Tendermint currently uses ed25519, and the SDK uses secp for accounts/signing tx. The LL spec currently proposes to use secp for everything instead. 

Additionally, we want to be able to recover the pubkey from the signature. For this we need to put the sign byte `v` into the signature: https://github.com/lazyledger/lazyledger-specs/blob/master/specs/data_structures.md#public-key-cryptography

**Comment by liamsi** [comment]
I'm actually in favour of keeping the original signature scheme tendermint currently uses! The main argument here was that secp is easier to verify on ethereum. 

But with the design of https://github.com/celestiaorg/quantum-gravity-bridge validators can additionally sign whatever and make it easily verifiable on ethereum.

**Comment by adlerjohn** [comment]
So long as the quantum gravity bridge is easily verifiable on Ethereum, what the main chain uses is _an implementation detail_.

**Comment by liamsi** [comment]
Let's close this then :)

**Comment by marbar3778** [comment]
Tendermint does support secp256k1 as a consensus signing key already, band actually uses them.
