### ISSUE TITLE
repo: create a celestia specific changelog

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-core#201]
Currently, we don  not really keep track of the LL specific changes in a changelog. 

Some changes we tracked in the tendermint and most we did not track at all. Keeping track of the changes in the tendermint changelog is not desired for many reasons: merge conflicts, hard to understand what the LL specific changes were, and much more. Having a separate LL-specific changelog is what we want.

**Comment by evan-forbes** [comment]
can close since #534
