### ISSUE TITLE
Fix nondeterministic test failures

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#216]
When Github's servers are busy, two of our tests begin to fail more frequently. The first is the CI e2e test, which reaches a timeout. The second is the `rpc/client` `TestTransportHandshake` test, which also reaches a timeout, but only because the rpc server fails to start due to the necessary ports still being used. 
```FAIL
E[2021-03-15|09:57:33.458] Stopped accept routine, as transport is closed module=p2p numPeers=0
E[2021-03-15|09:57:33.458] Error serving server                         err="accept tcp 127.0.0.1:35315: use of closed network connection"
E[2021-03-15|09:57:33.458] Error starting gRPC server                   err="accept tcp 127.0.0.1:37567: use of closed network connection
```

ref #208 and #178

**Comment by liamsi** [comment]
> The first is the CI e2e test, which reaches a timeout. 

For this we could look into increasing the right timeouts. I tried this but kinda rushed through it. I can look into it again.

**Comment by evan-forbes** [comment]
we haven't really had these issues lately, so closing for now
