### ISSUE TITLE
DA header optimizations

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-core#220]
Originally, specs aimed to optimize DA header size, but it turned out that this can be done on the implementation side without sacrificing simplicity in the calculation of the Merkle root, as described [here](https://github.com/lazyledger/lazyledger-specs/issues/140).

**Comment by evan-forbes** [comment]
@Wondertan @nashqueue can we update this issue?

**Comment by Wondertan** [comment]
I completely forgot the context behind this issue.

**Comment by nashqueue** [comment]
I think the optimization here is that you don't have to gossip tail padding rows .

**Comment by evan-forbes** [comment]
> I think the optimization here is that you don't have to gossip tail padding rows .

yeah exactly. probably not a huge deal, but could add up for larger squares

**Comment by evan-forbes** [comment]
closing because we have an issue in app for this, and all the logic lives there now https://github.com/celestiaorg/celestia-app/issues/826
