### ISSUE TITLE
Further benchmarks with Coded Merkle Tree instead of `RSMT2D`

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-core#228]
This might be a bit tricky, as we first need to figure out how to use namespaces in combination with a CMT but it might be worth doing more benchmarks (later) to better understand how both approaches comapre.

**Comment by evan-forbes** [comment]
ref: unfinished toy implementation https://github.com/evan-forbes/ncmt

**Comment by liamsi** [comment]
@evan-forbes this will be tackled via the PRs you are currently working on, right?

**Comment by liamsi** [comment]
Should we close this?

**Comment by adlerjohn** [comment]
yes.jpg
