### ISSUE TITLE
Use `sha256-simd` instead of native Golang implementation

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-core#272]
Having a computation speed-up through [easy to integrate lib](https://github.com/minio/sha256-simd) for such a widely used primitive is awesome.

**Comment by liamsi** [comment]
ref: https://github.com/lazyledger/lazyledger-core/pull/351

**Comment by evan-forbes** [comment]
also fwiw the speed up between the standard library and simd should be significantly smaller after go 1.21
