### ISSUE TITLE
Align Proposal struct with spec

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/celestia-core#303]
## Summary

Need to align `Proposal` struct fields with spec.

## Problem Definition

Current `Proposal`: https://github.com/lazyledger/lazyledger-core/blob/1a08b430a8885654b6e020ac588b1080e999170c/types/proposal.go#L25-L34

Proposal in specs: https://github.com/lazyledger/lazyledger-specs/blob/de5f4f74f56922e9fa735ef79d9e6e6492a2bad1/specs/proto/consensus.proto#L19-L36

## Fields left
- [ ] `last_header_hash`
- [ ] `fee_header`
- [ ] `stateCommitment`, `last_commit_hash`, `consensus_root`, `available_data_original_shares_used` - #305
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Wondertan** [comment]
@adlerjohn, does the last `intermediateStateRoot` equal to `stateCommitment` in Proposal?

**Comment by liamsi** [comment]
Note, the `POLRound` is used in tendermint and we can't simply remove it (as currently in the spec):
https://github.com/lazyledger/lazyledger-core/blob/1a08b430a8885654b6e020ac588b1080e999170c/types/proposal.go#L22-L25

**Comment by Wondertan** [comment]
So there are few fields missing:
1. `last_header_hash` - which should go together with BlockId replacements by @evan-forbes
2. `fee_header` - n/a for me, so @liamsi, I need your guidance here
3. `stateCommitment`, `last_commit_hash`, `consensus_root`, `available_data_original_shares_used` - luckily, can be added already.

Also, this is partially blocking me to implement #293 properly, so I will take care of 3

**Comment by liamsi** [comment]
> fee_header - n/a for me, so @liamsi, I need your guidance here

Can be ignored for now! It's only related to fee-burning and @adlerjohn wanted to write out an ADR for how that will look like. We could launch without fee-burning (even if this wouldn't be optimal).

**Comment by adlerjohn** [comment]
> does the last `intermediateStateRoot` equal to `stateCommitment` in Proposal?

Yes. Also, both are using deferred execution, so the intermediate state roots and the state commitment are after the _previous_ block's txs have been applied.

> why do we need to have `stateCommitment` in Proposal if there is one already in `intermediateStateRoots`

It's redundant information sure, but the performance overhead is basically zero and optimized implementations can remove them if they really want.

**Comment by adlerjohn** [comment]
> It's only related to fee-burning

Actually, the fee header _also_ provides information on the fee used for all transactions in a block! https://github.com/lazyledger/lazyledger-specs/blob/de5f4f74f56922e9fa735ef79d9e6e6492a2bad1/specs/data_structures.md#feeheader

Both the base rate and tip rate apply to all transactions in a block, instead of each tx having independent fee rates. Transactions instead only specify a _maximum_ fee rate. This scheme leads to improved UX, and actually provides second-price auction optimality under the assumption block proposers can't communicate with users at a mass scale to accept out-of-band payments (in practice, they can't).

**Comment by liamsi** [comment]
Ok, either way, tendermint doesn't have the concept of fees. This is up to the application and if we need this information in the proposal and header, we'd need to communicate it back to tendermint via abci. 

IMHO, what I said above still holds: we could launch without it, even if it would improve UX etc. It's still a relatively low priority and you can still ignore it @Wondertan; especially in the light of the upcoming MVP we've talked about today.

**Comment by liamsi** [comment]
I think we can close this. The decision to use tendermint as a blackbox with as little changes as possible was made in Kiev. We can revisit this after mainnet. (cc @adlerjohn)
