### ISSUE TITLE
Use secp256k1 keys in IPFS/libp2p instead of ed25519

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-core#342]
ref: https://github.com/lazyledger/lazyledger-core/pull/340#discussion_r635603484

**Comment by liamsi** [comment]
Also investigate if we should use the same key as the consensus key then (cc @adlerjohn).

**Comment by adlerjohn** [comment]
I don't think it's strictly necessary to use the same keys as consensus keys, but using the same keys for everything will probably simplify things, so sure.

**Comment by liamsi** [comment]
Copying over part of my comment from: https://github.com/lazyledger/lazyledger-core/pull/340#discussion_r635603484
> I'm back and fort on this. I do not care too much about secp vs ed25519 tbh but the general question if we should have one key for all purpose or several keys for different purposes. It might be not a bad idea to make it non-trivial to discover which validator runs which ipfs node for instance.

**Comment by liamsi** [comment]
Any thoughts on the above @adlerjohn ?

**Comment by adlerjohn** [comment]
Oh by "key" do you mean the actual secret key, or just the signing scheme. If the actual secret key, you probably don't want IPFS touching that.

**Comment by liamsi** [comment]
Yeah, the original discussion was around this:
https://github.com/lazyledger/lazyledger-core/blob/280cc82d7e9e2d698c0ee8623279cab6f102ee19/ipfs/defaults.go#L24-L25

**Comment by adlerjohn** [comment]
Does that PKI require the IPFS process to know about your secret key? Or just a public key? I imagine it doesn't work without a secret key, otherwise anyone could spoof. In that case, I'd be very hesitant to use the same key for both being a validator and IPFS.

**Comment by liamsi** [comment]
Yeah, it does not make any sense if IPFS does only know about the pubkey ...

**Comment by liamsi** [comment]
@Wondertan I've unassigned you because I think this one has super low priority.

**Comment by Wondertan** [comment]
@liamsi, ok
Although, I guess we can return to this question once we fully absorb IPFS, not to share Sk to IPFS process.

**Comment by liamsi** [comment]
My original concern was not about sharing the SK to the ipfs process but more so that identifying a validator will be the same as identifying the Ipfs node it is running. I think that is the question we should revisit first.

**Comment by liamsi** [comment]
This is not entirely the right place but it fits best here and I don't want to open a new issue for this: the tendermint p2p node key could and probably should be re-used in case we end up using libp2p more: https://github.com/lazyledger/lazyledger-core/blob/94c485374faa5948df3f6064ecbe08f4b83c4b00/p2p/key.go#L24-L31
This also defaults to ed25519 btw: https://github.com/lazyledger/lazyledger-core/blob/94c485374faa5948df3f6064ecbe08f4b83c4b00/p2p/key.go#L79

**Comment by Wondertan** [comment]
In order to match malicious nodes in Push DA with consensus/validaotor nodes, we need to have this. PubSub [encapsulates messages singing and verification](https://github.com/libp2p/go-libp2p-pubsub/blob/55d412efa7f5a734d2f926e0c7c948f0ab4def21/sign.go#L13) and not reinvent the wheel including this also makes sense

**Comment by liamsi** [comment]
> In order to match malicious nodes in Push DA with consensus/validaotor nodes, we need to have this. 

Matching those only makes sense if "malicious nodes in Push DA" trigger a slashable event. Otherwise we don't need to match both.

**Comment by Wondertan** [comment]
@liamsi, I reread my statement and understood that it misses an essential part of the explanation, so expanding on this:

I was wonderting about DoS vector concerns and proposing this to be part of the solution. But how? Luckily, we have a deterministic round-robin consensus where we know who is the proposer in advance. This allows the consensus layer to notify the p2p layer about shares origin, so it will just drop messages from any other origin preventing DoSing. Furthermore, if the expected origin act maliciously, e.g., provided a sample that is not part of the DataHash Merkle tree, we can then act accordingly on the consensus layer: recheck received DataHash is originated from the malicious validator and vote for nil or execute some slashing mechanism with the committee.

Going technical, I think of introducing options for Get/Retrieve data in the DA interface. For Push schema it will check PubSub messages origin, and for Pull it will ensure that we are connected to the origin peer.


Hope that makes sense.

/cc @musalbas for credit, as you initially pointed me to that on the previous dev call.

**Comment by liamsi** [comment]
> Luckily, we have a deterministic round-robin consensus where we know who is the proposer in advance. This allows the consensus layer to notify the p2p layer about shares origin, so it will just drop messages from any other origin preventing DoSing. 

This is not how simple gossip networks work though: only because a proposer is proposing a block it does not mean you will receive that data directly from that proposer (but rather from some peer you are connected to, could be the proposer but could be any validator / tendermint full node). 

Let's properly define all kinds of fraud proofs we want in the specification, together with slashable events they trigger (if any). Then we can decide on how to proceed with the slashing part. If we want to slash gossiping byzantine shares, then yes, the validator key should also be used for the p2p layer to make this attributable. I still think this is not a good idea and the consensus signing key should only be used for consensus messages and not for p2p concerns.

**Comment by Wondertan** [comment]
> This is not how simple gossip networks work though: only because a proposer is proposing a block it does not mean you will receive that data directly from that proposer (but rather from some peer you are connected to, could be the proposer but could be any validator / tendermint full node).

Idk specifically about Tm’s gossiping, but it is normal to sign a message before gossiping, so any relayer or recipient knows its origin. The recipient should both know the origin and related it got the message from. There is nothing complex here.

> Intuitively, I still think this is not a good idea and the consensus signing key should only be used for consensus messages and not for p2p concerns.

I fully agreed with such intuition, but this specific case changed my opinion slightly. It's clear that if running deterministic consensus with gossiping while tracking message origin allows hardening of security. Signing gossip messages with consensus key though doesn't mean using them everywhere, e.g., transport handshakes, etc

**Comment by liamsi** [comment]
Closing this as this is no longer relevant. The choice of keys can be argued in an issue/ADR in https://github.com/celestiaorg/celestia-node instead.
