### ISSUE TITLE
RetreiveBlockData should do DHT providing

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-core#394]
When a node retrieves a block it also stores it forever, as we currently don't have any block cleaning strategies. To contribute to the overall block's data discoverability, the node should provide and reprovide it to the network.

ref: #279

**Comment by liamsi** [comment]
This is also related to #182 #185 and a description of this should end up in: #435.

**Comment by liamsi** [comment]
This code will be moved to https://github.com/celestiaorg/celestia-node
IMO, we should reconsider the usage of the DHT in general as part of celestiaorg/celestia-node#1
