### ISSUE TITLE
Define CONTRIBUTING.md

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-core#407]
## Summary

Write concise and clear guidelines around the expected workflow. Basically contribution guidelines that also describe the expectations around: issues, ADRs and the relation to specs, PRs, reviews, chunking PRs into smaller pieces etc.

**Comment by rootulp** [comment]
FWIW we probably want a CONTRIBUTING.md in celestia-app too because that repo gets more external contributors than this one. We may take inspiration from https://github.com/celestiaorg/celestia-node/blob/main/CONTRIBUTING.md

**Comment by evan-forbes** [comment]
can have and use one in our .github somehow?

**Comment by rootulp** [comment]
https://github.com/celestiaorg/.github/blob/main/CONTRIBUTING.md

**Comment by evan-forbes** [comment]
closing for now as completed
