### ISSUE TITLE
Return a proof that a transaction or message has been included in a block

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#416]
## Summary

Return a proof that a transaction or message has been included in a block via rpc.

## Problem Definition
Currently, when asked to prove that a transaction has been included in a block, tendermint [loads the block](https://github.com/lazyledger/lazyledger-core/blob/7d4c1e966522425f35b4d980e9f0f746556a9768/rpc/core/tx.go#L39-L42) of a given height, and provide a simple proof. In order to provide the same functionality, celestia will have to selectively load the transaction data (#221) and extract a proof from IPFS. 

## Proposal

After saving and loading data via IPFS #374, finalizing node types, and being able to selectively load block data #221, we will be able to start implementing this proposal.

### Implementation

It will likely take 2-4 PRs to close this issue. One to handle extracting proofs from IPFS, one to search for and find tx and msgs, and at least one more to handle changing the actual rpc code.

**Comment by liamsi** [comment]
Note: this might impact the e2e tests in case they check for Tx with proofs. So in case we merge #218 and only store data in ipfs, we might have to disable proof checking until we fixed this issue at hand.

**Comment by evan-forbes** [comment]
We still have to return a proof that a `PayForMessage` is included in the block, but I don't think this issue is relevant any longer since it is focused on using IPFS to store block data.
