### ISSUE TITLE
Remove the `PartSetHeader` where possible

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#418]
## Summary

Remove the [`PartSetHeader`](https://github.com/lazyledger/lazyledger-core/blob/7d4c1e966522425f35b4d980e9f0f746556a9768/types/part_set.go#L94-L97).

## Details

As mentioned in #184, we now are propagating block data via IPFS and no longer need to do so via the `PartSetHeader`. After #218 and #374 are completed, we will have the necessary groundwork finished to actually remove the `PartSetHeader` completely. Complete removal is the next step to moving on with replacing the `BlockID` with the `Header` hash.

### Action Items
- [x]  #441 
- [x]  #456
- [ ] Remove from other structs/figure out exactly where it is needed

### References

part of completing #184

**Comment by Wondertan** [comment]
https://github.com/celestiaorg/lazyledger-core/pull/293 is also highly related. PartSetHeader is used extensively in consensus reactor and it might be necessary to implement block propagation first before removing PartSetHeader

**Comment by liamsi** [comment]
> and it might be necessary to implement block propagation first before removing PartSetHeader

It might also be possible to simply use the existing tendermint block propagation mechanism (maybe using erasure coded shares instead of current chunking) to unblock this and use the DAHeader instead of partsetheader where needed.

**Comment by liamsi** [comment]
ref: #389 #423

**Comment by evan-forbes** [comment]
Update: Instead of removing the `PartSetHeader `completely, will still use it, or something similar (#427 & #434), to propagate blocks during consensus. Regardless, we should still follow through with removal of the `PartSetHeader` where possible. Starting with #456.

**Comment by evan-forbes** [comment]
Update: Removing the `PartSetHeader` from `Vote` and `Commit` would require a refactor in the consensus reactor to change how the PSH is passed. It should be noted that while the `PartSetHeader` is still included in `Vote`, it is no longer signed over since #457

**Comment by liamsi** [comment]
> I think we should continue with the removal of the PSH from the Commit after we update to a newer version of tendermint.

Yeah, I agree there is no rush and it makes sense to update to a newer tendermint version first.

**Comment by evan-forbes** [comment]
we have since decided to keep tendermint as a black box, and complete removal of the PSH is no longer an option. That being said, we still have plans to experiment with removing it from the header and not signing over it #511
