### ISSUE TITLE
das light clients: dht mode

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-core#421]
## Summary

Make it at least easy to change for light clients to start in client mode:
https://github.com/celestiaorg/lazyledger-core/blob/7d4c1e966522425f35b4d980e9f0f746556a9768/ipfs/embedded.go#L52-L55

Investigate, if this shouldn't even be the default for light clients.

**Comment by Wondertan** [comment]
https://github.com/celestiaorg/lazyledger-core/issues/392

This is related. Also I think light client should be a DhT client by default and only server if configured to be so

**Comment by liamsi** [comment]
This code will be moved to https://github.com/celestiaorg/celestia-node
IMO, we should reconsider the usage of the DHT in general as part of celestiaorg/celestia-node#1
