### ISSUE TITLE
Add the ability to prune specific Celestia blocks in the IPFS store

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#442]
## Summary

Add the ability to delete a specific block's data in the embedded IPFS node's blockstore, and do so while pruning.

## Details

delete block data from the IPFS blockstore for a specific block height while pruning.
https://github.com/lazyledger/lazyledger-core/blob/004a1a9abcf95e5f0d5299f18f694146bc9473b4/store/store.go#L312-L316

### Action Items
- [ ] Implement the ability to remove a specific block's data
- [ ] Delete block data while pruning

### References

Will eventually be related to #393

**Comment by Wondertan** [comment]
@evan-forbes, @liamsi, what's the use case for pruning?

**Comment by evan-forbes** [comment]
> what's the use case for pruning?

anything that's not a storage node. This should have been included in #374 tbh

**Comment by liamsi** [comment]
If we still with the augment tendermint nodes to serve IPFS directly, then an additional feature I'd throw in the mix would be the ability to prune the erasure coding too. This will be a bit tricky as we still want storage nodes to recompute and serve these shares although they were deleted from the local store.

**Comment by evan-forbes** [comment]
closing as IPFS or erasured block data is no longer included in celestia-core
