### ISSUE TITLE
Decide on a mechanism to pick square size and communicate that to the app

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#454]
## Summary

We need to decide on exactly where and how the square size is determined, along with how that size communicated between celestia-core and celestia-app. This is necessary for the app to arrange messages in the in the square.

## Problem Definition

[Per the spec](https://github.com/celestiaorg/celestia-specs/blob/master/src/specs/data_structures.md#signedtransactiondatapayformessage), users actually sign over multiple [`SignedTransactionDataPayForMessage`](https://github.com/celestiaorg/celestia-specs/blob/master/src/specs/data_structures.md#signedtransactiondatapayformessage) when they want to submit a single message. The reason being that the commitments to the message that the transaction is paying for could change depending on the square size for the block.  The user therefore submits multiple signatures for different potential square sizes in order to ensure that one will be valid for whatever the square size ends up being for the upcoming block.

The app has to have a way of knowing the square size for a block so that it can pick which signature, and which version of `SignedTransactionDataPayForMessage`, should be passed back to celestia-core during `PreProcessTxs`.

This is a bit more complicated than it sounds, as optimally selecting the size and filling the square would require access to the mempool and being aware of the scheme mentioned in the first paragraph. celestia-core has access to the mempool, but is completely unaware of the types of transactions (staking, transfers, `SignedTransactionDataPayForMessage`, etc), let alone the scheme described in the above paragraphs, whereas the app is aware but doesn’t have direct access to the mempool.

While celestia-core should at least be able to estimate how many transactions could fit in the largest square size, it would have to be very conservative in that estimate as the current `PreProcessTxs` method has no way of knowing which transactions have and have not been processed. This could become a bigger issue when using non-interactive defaults, as more padding space will be necessary to accommodate large transactions.

## Proposal

Modify [`PreProcessTxsRequest`](https://github.com/lazyledger/lazyledger-core/blob/b8e72df9d005e5f19b6104adf7bc3c62e616eb6d/proto/tendermint/abci/types.proto#L123-L125) to include the square size 
```proto
message RequestPreprocessTxs {
  repeated bytes txs = 1;
  uint64 square_width = 2;
  uint64 cursor = 3;
}
```

Modify [`PreProcessTxsResponse`](https://github.com/lazyledger/lazyledger-core/blob/b8e72df9d005e5f19b6104adf7bc3c62e616eb6d/proto/tendermint/abci/types.proto#L272-L276) to include unprocessed Txs
```proto
message ResponsePreprocessTxs {
  repeated bytes            txs      = 1;
  tendermint.types.Messages messages = 2;
  repeated bytes   unprocessed_txs   = 3;
  uint64 cursor = 4;
}
```
This way, celestia-core only has to know if it has enough transactions in the mempool to probably justify using the largest square. If not, then select a smaller square size. Whatever square size is chosen by celestia-core is passed to the app via `PreProcessTxsRequest`, and let the app process messages using the provided square size. If there are leftover transactions, the app returns unprocessed transactions that can be re-inserted into the mempool. If there are no left over transactions, then celestia-core can reap more transactions and repeat the process (first described here #77).

An implementation of this proposal would also close #77 

edit: A major con of taking this approach is that it makes this fork's version of the ABCI less general, along with deviating further from tendermint

### Implementation

If this proposal is approved, the celestia-core and celestia-app portions should likely be developed in tandem due to their tight coupling.

**Comment by liamsi** [comment]
Wow, thanks for this! We should think this through carefully (also in the light of that abci++ will land eventually in tendermint, there Block.Data is passed in and returned) but this issue is exemplary.

**Comment by evan-forbes** [comment]
relevant proposal [#7750](https://github.com/tendermint/tendermint/issues/7750)

**Comment by evan-forbes** [comment]
this was completed in https://github.com/celestiaorg/celestia-app/pull/224 and https://github.com/celestiaorg/celestia-app/pull/231
