### ISSUE TITLE
Fraud Proofs Tracking Issue

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#459]
Per the spec, Celestia will support two types of native fraud proofs, [Bad encoding](https://github.com/celestiaorg/celestia-specs/blob/master/src/specs/data_structures.md#badencodingfraudproof) and State. This will require quite a few changes across more than one repo, and this issue is meant to track those satellite issues required to properly implement fraud proofs. 

### BadEncodingFraudProof
- [x] #461 

### ~~StateFraudProof~~ we will focus on state fraud proofs later
- [x] https://github.com/celestiaorg/celestia-specs/pull/190
- [ ] #462 
- [x] #481
- [ ] #480

### MessageInclusionFraudProof
- [ ] https://github.com/celestiaorg/celestia-core/issues/519

**Comment by nusret1996** [comment]
[PR #190](https://github.com/celestiaorg/celestia-specs/pull/190) was created to add state fraud proofs to spec.

**Comment by evan-forbes** [comment]
ref [#132](https://github.com/celestiaorg/optimint/issues/132)

**Comment by liamsi** [comment]
I think we can close this here. BadEncodingFraudProofs will be implemented in node/the DA layer only and state fraud proofs are not happening before the mainnet milestone.
