### ISSUE TITLE
Implement BadEncodingFraudProof 

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#461]
## Summary

We need to implement [BadEncodingFraudProof](https://github.com/celestiaorg/celestia-specs/blob/master/src/specs/data_structures.md#badencodingfraudproof), which indicates to light clients that there was some number of shares committed to that were not encoded properly.

## Details

BadEncodingFraudProof will likely never actually end up on-chain, as a valid proof would mean that at least 2/3 of the validators have behaved in a malicious manor. Despite that, storage nodes still need a way to indicate to light clients that something is awry. They will do this with BadEncodingFraudProofs.

Eventually, the implementation of `BadEncodingFraudProof` could end up in a different repo, but until the full picture for all nodes types is fleshed out, I think it makes sense to keep it here.

### Action Items
- [ ] Add the proto message for `BadEncodingFraudProofs` and [`ShareProof`](https://github.com/celestiaorg/celestia-specs/blob/master/src/specs/data_structures.md#shareproof)
- [ ] Code to create the `BadEncodingProof`s from some number of shares.

### References
tracking issue #459
blocked by #460
also closes #222

**Comment by musalbas** [comment]
Should this be moved to celestia-node?

**Comment by liamsi** [comment]
Yeah, can be closed in favour of https://github.com/celestiaorg/celestia-node/issues/4 and https://github.com/celestiaorg/celestia-node/issues/84

**Comment by musalbas** [comment]
How about https://github.com/celestiaorg/celestia-core/issues/459? And which is of these issues is tracked for testnet?
