### ISSUE TITLE
Use Wrapped Txs

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#462]
## Summary

Linking a given transaction to an intermediate state root is crucial for creating state fraud proofs. When merging shares, some meta data [outlined in the spec](https://github.com/celestiaorg/celestia-specs/blob/ec98170398dfc6394423ee79b00b71038879e211/src/specs/data_structures.md#wrappedtransaction) is needed to link txs and isrs, and should be preserved.

## Details

Due to encoding and decoding of Txs and ISRs, swapping them for WrappedTxs and WrappedISRs will be slightly more involved than simply adding the meta data. We will also need some helper functions to aid in finding linked Txs and ISRs. 

### Action Items
- [ ] Create the proto types for WrappedTxs and WrappedISRs
- [ ] Implement methods to merge into shares
- [ ] Modify current share splitting functions to accommodate new types and meta data
- [ ] Replace usage elsewhere where necessary in celestia-core
- [ ] Create helper functions to find linked transactions and intermediate state roots

### References

tracking issue #459

**Comment by evan-forbes** [comment]
for an easy solution, since we already wrap malleated txs with their original hash, we can simply add the message location to that struct.

**Comment by liamsi** [comment]
Can we add a very short ADR for this as well. I'm also wondering what the best way to document this. Maybe the ADR could simply reference and slightly augment the existing spec when describing the decision here?

**Comment by evan-forbes** [comment]
> Can we add a very short ADR for this as well. I'm also wondering what the best way to document this. Maybe the ADR could simply reference and slightly augment the existing spec when describing the decision here?

yeah that's a great idea. The implementation specifically for wrapped txs is very simple, but I agree that an ADR for how/why wrapped txs are used in the app. Specifically their usage when performing message inclusion checks and their involvement in non-interactive defaults
