### ISSUE TITLE
Upgrade from upstream

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#492]
We will have to update our fork of the latest version of tendermint if we want to take advantage of security patches and upcoming features such as ABCI++.

Unfortunately, due to significant refactoring in tendermint since we forked, updating will be a little bit more complicated than strictly rebasing our changes onto the latest master branch. 

This should likely be done after as much code as possible has been moved to the celestia-node repo, and we should also document each of the changes #482.

As a bonus, we should also think about streamlining the process of merging future updates.

**Comment by marbar3778** [comment]
assigning to myself. I am working on this. 

I am just about done with the merge conflicts, down to 60 out of 300. Then will fix tests and compare with changes here and in Tendermint. I should have a PR up later today.

**Comment by evan-forbes** [comment]
closed by the merging of #534
