### ISSUE TITLE
Remove the `DataAvailabilityHeader` from `Block`

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#512]
## Summary

We don't strictly need the `DataAvailabilityHeader` to be in `Block`, so we can remove it.

## Problem Definition

Since the `DataAvailabilityHeader` does not have to be in `Block`, and validators already have to regenerate the DataAvailabilityHeader to verify the block, then we could optimize the size of the `Block` struct by removing the `DataAvailabilityHeader` field. 

## Proposal

Instead of passing the `DataAvailabilityHeader` with the `Block`, we can remove the `DataAvailabilityHeader` field and instead generate it after receiving the `Block`. The `DataAvailabilityHeader` would then be passed to any function that needs it, or regenerated. 

Note: this is purely an optimization, and should therefore not be prioritized until later. This could also be accomplished in conjunction with #505, as that will be required to fully remove the DAH from the block

### Implementation
- [ ] Remove the `DataAvailabilityHeader` from block
- [ ] Regenerate the DAH when verifying the block
- [ ] Save the DAH in `BlockMeta` by passing it the `SaveBlock` method
- [ ] Pass the DAH to `PutBlock` (assuming we keep PutBlock at all)

blocked by:
#518
#505

**Comment by adlerjohn** [comment]
Makes sense

**Comment by evan-forbes** [comment]
closed by the merging of #534
