### ISSUE TITLE
Refactor DAH generation to give the user more control over what happens to the EDS

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#538]
## Summary

Currently the extended data square is being garbage collected after it is created during the generation of a new `DataAvailabilityHeader`. We should make it so that this decision is not forced on the user. 

## Details

The user (celestia-node) might want to save the extended data square, so we should change how we generate `DataAvailabilityHeaders` to allow that to occur

### Action Items
- [ ] Break up `NewDataAvailabilityHeader` func into two pieces

**Comment by liamsi** [comment]
Am I understanding this correctly: this is simply about exposing a method that can be used as a library in Celestia node? Or is there more to it?

**Comment by evan-forbes** [comment]
whoops, must have missed this comment, but I think we covered it in #539 

also can close w/ the merge of #534
