### ISSUE TITLE
ci: dockerhub for core 

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-core#554]
As #553 has exposed the need to start creating the dockerhub for celestia, this is an issue to make it happen and track the further progress

**Comment by evan-forbes** [comment]
@Bidon15 can we close this since we're just using github's container repository for celestia-app, or do we still need this for celestia-core as well?

**Comment by Bidon15** [comment]
Yes. Closing this as irrelevant
Thanks for flagging!
