### ISSUE TITLE
Patch upstream to keep our modified proto files

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#566]
## Summary
Upstream master switched to strictly using the tendermint spec as the single source of proto files [#6976](https://github.com/tendermint/tendermint/commit/19ec4a532239be8124a9ed2ed5891cefa4eef9a4#diff-66c5d2694b0ff925b58c4d934298d7b1a1845ccbec124704a0a6fd22a3cbb6eb). We need to create a patch that will do the same, except keep our modifications to those files.

### References

[#6976](https://github.com/tendermint/tendermint/commit/19ec4a532239be8124a9ed2ed5891cefa4eef9a4#diff-66c5d2694b0ff925b58c4d934298d7b1a1845ccbec124704a0a6fd22a3cbb6eb)

[#343](https://github.com/tendermint/spec/issues/343)

**Comment by adlerjohn** [comment]
Repo at: https://github.com/celestiaorg/spec

**Comment by adlerjohn** [comment]
Is this issue needed anymore?

**Comment by SweeXordious** [comment]
@evan-forbes Hello, can I take this on?

**Comment by evan-forbes** [comment]
Certainly!
