### ISSUE TITLE
Debug why `WirePayForMessage`s are not removed from the mempool when rechecking transactions

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#584]
## Summary

In #581, we introduced a temporary fix to remove `WirePayForMessage`s from the mempool. For a long term solution, we need to debug why the transactions are not removed when [rechecking](https://github.com/celestiaorg/celestia-core/blob/1609bde2a41604fff1ebcb202e0e9cce1048fb3b/state/execution.go#L286-L293) the transactions in the mempool after they are committed. 

## Details

The temporary fix introduced in #582 relies on a wrapped transaction type that attaches the hash of the parent `WirePayForMessage` transaction to the child `MsgPayForMessage`. This hash is then used to identify and remove the old `WirePayForMessage` from the mempool after the `MsgPayForMessage` is committed to.

This solution has a lot of downsides, and is only meant to patch the bug until we can debug why the existing solution isn't working as expected.

### References

Hacky solution issue #581, core PRs #582 and #583, along with the app PR [#149](https://github.com/celestiaorg/lazyledger-app/pull/149)

**Comment by adlerjohn** [comment]
Can you clarify what a "parent" tx and the parent tx hash vs the current (?) tx hash is?

**Comment by evan-forbes** [comment]
Heyo https://github.com/cosmos/cosmos-sdk/pull/12060

**Comment by evan-forbes** [comment]
I think we can close this since our release of v0.46.0 of the sdk has the above fix, and will be included after we hardfork mamaki
