### ISSUE TITLE
Create ABCI++ branch with celestia specific changes

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#623]
We should create a release branch that incorporates all of the necessary celestia specific changes with all of the changes made so far with upstream's ABCI++ branch

**Comment by liamsi** [comment]
What is the status/purpose of this? If we want to diff between this and upstream, we can do so from our main branch and look at the abci++ changes manually?

**Comment by evan-forbes** [comment]
I think was meant to be closed by #631

> Closes https://github.com/celestiaorg/celestia-core/issues/623

but the format was wrong so the github hook didn't pick up on it. Any future changes related to ABCI++ should be incorporated via cherry-picking changes from an old release branch onto a branch based on some stable/release branch of tendermint
