### ISSUE TITLE
Consider removing unused types from block data

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#649]
We do not have plans to use certain types currently in the block data.

https://github.com/celestiaorg/celestia-core/blob/86b292b620b34a360fe3fc754ec55d0b42bec400/types/block.go#L1010-L1038

We could get rid of ISRs, as we are not planning on implementing state fraud proofs until after mainnet. We can of course add them back in when we do. Might be able to safely get rid of `Evidence` as well.

**Comment by liamsi** [comment]
If we do this we might simply skip the field number in protobuf to reserve the current position. Everywhere else we can just remove them.

**Comment by liamsi** [comment]
besides ISRs is there anything else we plan to remove?
