### ISSUE TITLE
Support the ability for validators to validate blocks via data availability proofs

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/celestia-core#65]
A current limitation of Tendermint is that before a block has consensus from the validator set, it is only distributed among the validator set. This makes it not easily possible for these validators to validate the block via a data availability proof, because the minimum number of light client assumption is less likely to hold. Consider publishing blocks to the wider network before they have consensus.

**Comment by liamsi** [comment]
According to @marbar3778 the block is distributed not only among the validators. Other nodes get to see the block before it has consensus too (only validators add their signatures though). This could be as simple as adding in the DA checks (and making Tx execution optional).

**Comment by liamsi** [comment]
We decided that validators will not do DAS. Hence, closing. (cc @musalbas @adlerjohn)
