### ISSUE TITLE
libs/pubsub: panic caused by incorrect subscription cancellation handling

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-core#667]
On the line https://github.com/celestiaorg/celestia-core/blob/0d0baeb97f62a7f83838bb6cad7e9a3847a3325a/libs/pubsub/pubsub.go#L222 we return double `nil`, subsequently on the line https://github.com/celestiaorg/celestia-core/blob/0d0baeb97f62a7f83838bb6cad7e9a3847a3325a/internal/rpc/core/events.go#L41 we proceed, and panic on the line https://github.com/celestiaorg/celestia-core/blob/0d0baeb97f62a7f83838bb6cad7e9a3847a3325a/internal/rpc/core/events.go#L50, which calls a method on a `nil` `sub`.

This can happen on the latest and past releases. Upstream Tendermint fixed this a while ago, but for celestia-node it breaks the test, so might be worth fixing already. 

Fixing can be done just by returning the arbitrary error on line https://github.com/celestiaorg/celestia-core/blob/0d0baeb97f62a7f83838bb6cad7e9a3847a3325a/libs/pubsub/pubsub.go#L222

**Comment by liamsi** [comment]
@evan-forbes are you with cherry picking the pubsub changes?

**Comment by adlerjohn** [comment]
#715 didn't fix either?

**Comment by liamsi** [comment]
No 😢 I'd suggest to not spend more time on this and instead upgrade to tendermint 0.35 asap instead.

**Comment by Wondertan** [comment]
Right

**Comment by adlerjohn** [comment]
Does this resolve this blocker? https://github.com/celestiaorg/celestia-node/blob/7af0c47a25ab892d0f3da867c912496ebf6db137/nodebuilder/node_bridge_test.go#L19

@Wondertan

**Comment by Wondertan** [comment]
Could be, has to be tested
