### ISSUE TITLE
Remove `IntermediateStateRoots` from the block data

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#668]
Until we have firm plans for state fraud proofs, we should remove `IntermediateStateRoots` from the block data, as they are unused and could be confusing for new readers. However, we should likely keep the reserved namespace ID for them, as we will add them back in eventually.

**Comment by liamsi** [comment]
In the protbuf, we could add a "placeholder" by skipping a fieldnumber s.t. if we ever implement state fraud proofs in the base layer we can do it without breaking the proto. Just an idea. We could also just think about it whenever we need it.

**Comment by evan-forbes** [comment]
can close
