### ISSUE TITLE
Document workflow from upstream

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#675]
We currently use a weird workflow, since we only work on a stable release of tendermint, and don't want to force push the master branch. We should document this better for future contributors.

**Comment by adlerjohn** [comment]
It looks like there's an inconsistency in which branch PRs get merged to. Some recent ones have been merged into `master`, but not then merged into the v0.34.x branch.

**Comment by rootulp** [comment]
I'm not sure what additional documentation we need besides https://github.com/celestiaorg/celestia-core#branches so closing this. Please re-open with additional details if desired.
