### ISSUE TITLE
Update linter version in v0.34 branch and fix typos

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/celestia-core#678]
https://github.com/celestiaorg/celestia-core/pull/637/commits/35178048f0fef2d80a0346f28c7687be75c3db11

**Comment by adlerjohn** [comment]
Is this still needed @evan-forbes, or can we close since v0.34 is no longer in use?

**Comment by rootulp** [comment]
https://github.com/celestiaorg/celestia-core/tree/v0.34.x-celestia will be used for mainnet. Versions of go and golangci-lint in this repo match upstream. We do still need to fix lint issues which can be tracked in https://github.com/celestiaorg/celestia-core/issues/1000

Ref:
1. https://github.com/celestiaorg/celestia-core/blob/v0.34.x-celestia/.github/workflows/lint.yml
2. https://github.com/cometbft/cometbft/blob/v0.34.27/.github/workflows/lint.yml
