### ISSUE TITLE
Consider not relying on the consts package while splitting shares

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#719]
as mentioned in these comments, https://github.com/celestiaorg/celestia-core/pull/637#discussion_r841523029 and https://github.com/celestiaorg/celestia-core/pull/637#discussion_r840647492, when splitting shares, instead of using the consts package, we could load the required params into the share writer itself to make the code more reusable.

**Comment by rootulp** [comment]
After reading the linked comments, I still don't understand the motivation behind this issue. @Wondertan does celestia-node want to use the share splitting code with a requirement that prevents it from depending on consts package?

**Comment by rootulp** [comment]
Closing this b/c lack of motivation. The relevant code has mostly migrated to celestia-app. Feel free to re-open there if it's something we still want to do.
