### ISSUE TITLE
Ensure that all namespaces can be used in the data square 

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#722]
Even with checks added to the `MsgPayForData` transactions, it would still be possible for a validator to include an invalid `MsgPayForData` that submits a message that uses reserved namespaces, such as the `TailPaddingNamespaceID` and the `ParitySharesNamespaceID`. We need to either:
- test that including these namespaces will not impact the functionality of other nodes when expanding the data square to create the data hash
- include a check during `ProcessProposal` to ensure that these namespaces are not used by messages in a proposal block

**Comment by rootulp** [comment]
This issue appears resolved by https://github.com/celestiaorg/celestia-app/pull/592/files in particular https://github.com/celestiaorg/celestia-app/blob/main/app/test/process_proposal_test.go#L184

**Comment by evan-forbes** [comment]
yeah we can close
