### ISSUE TITLE
中文版 Chinese Version for markdown i want2help write

### ISSUE THREAD

**Issue by willshion** [celestiaorg/celestia-core#729]
## Summary
title

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
Hi @willshion , thanks for opening this issue! Are you proposing writing a Chinese translation for the Markdown files in this repo? Which files would you consider translating besides the README?

**Comment by rootulp** [comment]
Closing due to lack of response
