### ISSUE TITLE
feature: share encoding versioning

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-core#759]
## Summary

> [We may want to consider versioning the shares in order to allow for backwards-compatibility for on-chain smart contracts or programs that need to parse the shares but are not upgradeable.](https://github.com/celestiaorg/celestia-core/issues/757#issuecomment-1136027431)

originally posted by @musalbas on #757 

## Problem Definition

see above

## Proposal

A version byte per share?

**Comment by liamsi** [comment]
I do think adding a byte on a per share level for very specific edge-cases is a optimizing for the wrong thing. But if this is a strict requirement, then yes, there is no way around this. If we already add some Meta Data to the share, we can actually look into putting this into CIDs instead as @Wondertan suggested. 
Also I'd like to hear what @adlerjohn thinks about this.

**Comment by liamsi** [comment]
> backwards-compatibility for on-chain smart contracts

@musalbas: smart contracts can be upgraded, right?

> programs that need to parse the shares but are not upgradeable

Maybe we should not design our use of block space around other people's bad design decisions? What is a non-upgradeable program that we should care about for instance?

**Comment by adlerjohn** [comment]
It's not needed unless we plan on changing this after mainnet launch. Anything before then can be broken at will.

**Comment by musalbas** [comment]
Yes, we're talking about it possibly changing after mainnet.

**Comment by rootulp** [comment]
Safe to close this issue in favor of https://github.com/celestiaorg/celestia-core/issues/839 ?

**Comment by rootulp** [comment]
Closing in favor of https://github.com/celestiaorg/celestia-core/issues/839 and https://github.com/celestiaorg/celestia-app/issues/659
