### ISSUE TITLE
Adopt Reaping from the mempool to max square size

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-core#77]
## Summary

Current `mempool.ReapMaxDataBytes` logic doesn't seem like the right approach for LL core as we need to reap as many Tx as shares would fit into the max square size.

## Problem Definition

The current mechanism needs to be based on the max square size instead of gas only:
https://github.com/lazyledger/lazyledger-core/blob/6d99bdda1b59d1b1e5b6c83635ad879bfdffb19e/state/execution.go#L103-L110

## Proposal

One rough idea @adlerjohn and I talked about is the following approach:
 - reap as many tx from the mempool that would definitely fit into the max square size and then
 - figure out a smallest square that fits all shares
 - if it doesn't fit (because of padding), double the square size and try again

This probably terminates after one or two iterations but it would be could if can formalize this a bit further and have small proof for the upper bound of iterations.

ref: https://github.com/lazyledger/lazyledger-specs/pull/79

**Comment by liamsi** [comment]
In this context we also need to reserve space for the intermediate state roots:
Copied from: https://github.com/lazyledger/lazyledger-core/pull/83#discussion_r513535480

**Comment by evan-forbes** [comment]
relevant proposal [#7750](https://github.com/tendermint/tendermint/issues/7750)

**Comment by evan-forbes** [comment]
the current approach to this is do reap more txs than can fit in the block assuming that most of them are still valid, so I think we can close this issue
