### ISSUE TITLE
Potenial bug with Txs spanning > 2 shares

### ISSUE THREAD

**Issue by mindstyle85** [celestiaorg/celestia-core#797]
Hey guys, still seeing this:

```
celestia-appd q tx 4AB987292DA8AEFDA3FA01B6FC6C8C6DB7AB741CE5A24470C07DBBB87B8A96FF --node https://rpc-mamaki.pops.one

Error: RPC error -32603 - Internal error: transaction spanned more than two shares, this is not yet supported
```

On:
```
celestia-appd version
0.5.5-beta-1
```

**Comment by evan-forbes** [comment]
I was unable to recreate this bug query my nodes on v0.5.5-beta-1 or v0.5.4. Is there a chance that the node behind https://rpc-mamaki.pops.one is still using v0.5.3 or below?

**Comment by mindstyle85** [comment]
ah youre right, that one hasnt been updated although i thought it was, will close this and update our rpc node
