### ISSUE TITLE
Multiple Mergify configs

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-core#816]
## Description

CI is failing on https://github.com/celestiaorg/celestia-core/pull/815/checks?check_run_id=7655642418

## Screenshot

<img width="648" alt="Screen Shot 2022-08-03 at 11 54 58 AM" src="https://user-images.githubusercontent.com/3699047/182654283-d7a7f225-9c71-4d35-82e2-2b684b3f3647.png">

**Comment by evan-forbes** [comment]
I front ran you :slightly_smiling_face: #813

**Comment by evan-forbes** [comment]
we can just use this one tho
