### ISSUE TITLE
Remove implicit message sorting

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-core#826]
We want to remove implicit message sorting here:

https://github.com/celestiaorg/celestia-core/blob/60b268964c495926b294e69b488f10a7293f5ace/types/block.go#L1166

Motivation in https://github.com/celestiaorg/celestia-app/issues/595. This issue is blocked on this code being moved to celestia-app

**Comment by evan-forbes** [comment]
We want to move as much of this code to app as possible, which includes this implicit sorting. We should be able to close this issue after we move it there and delete it here.

**Comment by rootulp** [comment]
This code has been moved to celestia-app but I don't see a `SortMessages()` invocation. 

Note: we do sort message indexes here: https://github.com/celestiaorg/celestia-app/blob/595fd3bc1bdbf9f0ab01a8ef6ce2a2156a7e0cec/pkg/shares/share_splitting.go#L40-L44
