### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-core#833]
## Summary

This repo could benefit from a guide on how to cut a new release

## Problem Definition

Current release process is to ask @evan-forbes or @liamsi to cut a new release. However this process has a low bus factor. It would be nice if the steps were documented so that any team member with permission is able to self-service cut a new release.

## Proposal

Steps documented in a Markdown file (e.g. `README.md`) that describe the release process, who has permission to cut a release, and any non standard release steps. Something like:

1. Create a release in Github UI
1. Upgrade to the new celestia-core version in cosmos-sdk and celestia-app

**Comment by rootulp** [comment]
Feedback from @evan-forbes is that we should copy what https://github.com/tendermint/tendermint does

**Comment by evan-forbes** [comment]
as discussed synchronously, the main issue is that even the smallest of changes can unintentionally be consensus breaking.

imo, before we change this process, we need extensive tests like in https://github.com/celestiaorg/celestia-app/issues/313

I'd also advocate for slowly rolling out features to a minority of nodes if at all possible. Whether this be a release candidate, specifically mentioning that we do not advise validators to update unless they all update, or postponing as many changes as possible until the next hardfork.

**Comment by rootulp** [comment]
> before we change this process, we need extensive tests like in https://github.com/celestiaorg/celestia-app/issues/313

+1 more tests if it gives us additional confidence. And for clarity, I don't intend on changing the process. This issue is an attempt to make the current process discoverable and repeatable by new teammates (if possible).

**Comment by rootulp** [comment]
The release process is to cut a release via Github UI. 

1. Navigate to https://github.com/celestiaorg/celestia-core/releases/new
2. Create a new tag based on the previous released version. For example, if the most recent release of celestia-core is `v1.9.0-tm-v0.34.20` then the next tag may be `v1.10.0-tm-v0.34.20`.
3. Click **Generate release notes**
4. Click **Publish release**
