### ISSUE TITLE
Move share constants to celestia-app

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-core#841]
## Description

celestia-core defines constants in: https://github.com/celestiaorg/celestia-core/blob/v0.34.x-celestia/pkg/consts/consts.go 

Tendermint doesn't need to know about some of these constants so they can be moved to celestia-app. The benefit to moving them is it minimizes the diff between celestia-core and tendermint and moves more Celestia-specific logic to celestia-app.

One potential destination is https://github.com/celestiaorg/celestia-app/tree/evan/non-interactive-defaults-feature/pkg/appconsts

## Proposal

- [ ] Define the list of constants that can be moved (e.g. https://github.com/celestiaorg/celestia-core/blob/v0.34.x-celestia/pkg/consts/consts.go#L52)
- [ ] Move the list of constants from celestia-core to celestia-app

**Comment by evan-forbes** [comment]
now that we're planning on moving the share encoding/decoding code to a different repo, we will have to move these constants to that repo as well

**Comment by rootulp** [comment]
share encoding code may end up in celestia-app medium term so these constants may be moved there instead of a new share repo
