### ISSUE TITLE
Rename `OriginalSquareSize` to `SquareSize`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-core#853]
Motivation in https://github.com/celestiaorg/celestia-app/issues/687

https://github.com/celestiaorg/celestia-core/blob/204597c40e3991e343bbd9c765d6354f007df203/types/block.go#L1034

**Comment by HoytRen** [comment]
Hello rootulp, are you working on this? If you are busy on something else, I want to have a try since this seems suitable for a new developer.

**Comment by HoytRen** [comment]
Should I change celestia-app so that it's not break?

**Comment by evan-forbes** [comment]
> Should I change celestia-app so that it's not break?

good question, we can fix celestia-app when we upgrade to a version of core that has this fix
