### ISSUE TITLE
Disable LGTM workflow

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-core#862]
## Context
We currently have an LGTM analysis workflow but if you navigate to the Details link, it says LGTM is shutting down. Ref: https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

## Proposal

We likely want to disable LGTM and enable Github code scanning. LGTM doesn't appear as a workflow in https://github.com/celestiaorg/celestia-core/tree/v0.34.x-celestia/.github/workflows so we may need an admin to disable it on https://lgtm.com/projects/g/celestiaorg/celestia-core/rev/pr-5a24924f1da5617777b782d3fae679a4db189f0d

## Screenshots

<img width="1238" alt="Screen Shot 2022-09-14 at 5 50 04 PM" src="https://user-images.githubusercontent.com/3699047/190269751-8d3c6cc9-c74d-4f65-9bd5-f1bf0fc4c445.png">

---

<img width="935" alt="Screen Shot 2022-09-14 at 5 54 33 PM" src="https://user-images.githubusercontent.com/3699047/190269852-f31135ae-1dc7-46ad-a74d-bfc5975a9848.png">

**Comment by adlerjohn** [comment]
cc @liamsi

**Comment by liamsi** [comment]
removed
