### ISSUE TITLE
Consider checking TypeURL in `UnwrapMalleatedTx`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-core#880]
## Context
While discussing upcoming WirePFB refactors, @evan-forbes and I discussed adding a check to `UnwrapMalleatedTx` to verify the TypeURL of a WirePFB. Something like
https://github.com/celestiaorg/celestia-app/blob/6ba7873533f09c8ea8ccfe671eee6b4a65c8903c/app/process_proposal.go#L88

## Problem
https://github.com/celestiaorg/celestia-core/blob/b7a7c1ab37fde91f9687b5c1c4766119e7b71db5/types/tx.go#L205

doesn't currently perform any checks for TypeURL so it's possible to unwrap a tx that isn't a WirePFB

## Proposal
Add a TypeURL check

**Comment by rootulp** [comment]
On re-review, TypeURL is an SDK concept and it doesn't seem desirable to introduce a Cosmos SDK import in celestia-core.

**Comment by evan-forbes** [comment]
the sdk uses this https://github.com/golang/protobuf/blob/v1.5.2/proto/registry.go#L264, which we should be able to use without importing the sdk. 

That is deprecated on closer inspection tho... we will eventually have to switch to some other equivalent depending on how we generate things in the future.

**Comment by evan-forbes** [comment]
I think we can close this now, as we're using four character strings as an added field. #893
