### ISSUE TITLE
Resolve go-staticcheck warnings for deprecated "io/ioutil" usage

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-core#889]
<img width="1024" alt="Screenshot 2022-11-17 at 3 10 43 PM" src="https://user-images.githubusercontent.com/3699047/202549317-94f4de7c-8f2d-4e78-8845-9574c843bb7a.png">

**Comment by cmwaters** [comment]
This can be solved if we simply update to the latest v0.34.x version

**Comment by rootulp** [comment]
Closing in favor of https://github.com/celestiaorg/celestia-core/issues/870
