### ISSUE TITLE
QGB add custom query to the app to generate shares inclusion proofs

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-core#891]
As per https://github.com/celestiaorg/celestia-app/issues/956, we will need to add RPC support for the shares inclusion proofs using custom queries.
These latter will be used to call Celestia-app, generate shares inclusion proofs, and return them to the user.

**Comment by rootulp** [comment]
> for the shares inclusion proofs

is there an ADR or document I can read to learn what this covers?

**Comment by SweeXordious** [comment]
There is none at the moment, I guess.  The idea is to be able to create proofs for ranges of shares so that they can be verified in the QGB smart contract.

So, the proofs will be as follow:

- shares NMT inclusion proof to row roots (implemented in the app)
- row roots  inclusion proof to data root (implemented in the app)
- data roots inclusion proof to commitment (implemented in core)

Let me know if you have other questions, or if I am not clear enough
