### ISSUE TITLE
Proposal: Wrap each transaction with a type tag

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#903]
it was suggested that instead of only wrapping malleated and blob transactions, that we wrap each type of transaction with a single byte tag that we could use to further parse each type. This is subtly different from what we are doing in #893, where we introduce a string tag only for specific types.

**Comment by rootulp** [comment]
Related: https://github.com/celestiaorg/celestia-app/issues/1105

**Comment by evan-forbes** [comment]
lol I might have created a duplicate issue. I like #1105 better tho, so I think we can close this
