### ISSUE TITLE
Remove the generated mocks CI check

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#915]
The crux is that v0.34.23 changes the `Peer` interface but in order to make it non-breaking, a new interface was introduced:
```go
type EnvelopeSender interface {
	SendEnvelope(Envelope) bool
	TrySendEnvelope(Envelope) bool
}
```
and a few shim functions were added to support the old `Peer` which has `Send` and the new `Peer` which has `SendEnvelope` (NOTE: in v0.37 the interface is then broken).

I'm going to merge this now but either we:
1. rollback the tests in https://github.com/tendermint/tendermint/commit/bdedf2ec205bff409535b636496eb3c5f2aa7fc6#diff-845bad6985bed7731e25d658c3bfbc7f5639ebf2a739b8074fe9614ce71941bc that change `Send` to `SendEnvelope`
2. Turn off the mockery checker
3. Bring the change in v0.37 forward such that the `Peer` interface has `SendEnvelope` as well.

_Originally posted by @cmwaters in https://github.com/celestiaorg/celestia-core/issues/906#issuecomment-1348036502_

**Comment by cmwaters** [comment]
Closing by https://github.com/celestiaorg/celestia-core/pull/917
