### ISSUE TITLE
blocksync: block validation does not include data hash.

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-core#926]
## Summary

The `ValidateBasic` check in `Block` has the data hash check removed because a different calculation is used and the check happens instead in `ProcessProposal` of the application and not within Tendermint.

Blocksync doesn't call `ProcessProposal`. This means that nodes syncing don't check the `Data` they receive with the hash in the header. This means that malicious nodes could fabricate blocks packed with extra unused data or worse they could include transactions that lead to a different app hash causing the syncing node to panic when `ApplyBlock` errors (because of an app hash mismatch). 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
@sergio-mena and others have discussed this in the past, and as you've pointed out, I do think that in the way that we've replaced the data root, this is major bug!
