### ISSUE TITLE
Add unit tests for the ShareProof and RowProof

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#953]
The verification looks good to me although It'd pay to have a few more eyes.

Do you plan on writing unit tests for the share proof and row proof?

_Originally posted by @cmwaters in https://github.com/celestiaorg/celestia-core/pull/950#pullrequestreview-1274861448_

in #950, we moved some proofs that were originally introduced in #878. At that time, we didn't introduce unit tests since they were being tested in the app, and are essentially wrappers around the nmt proof. However, it would still be nice to have unit tests here to at least ensure that we don't accidentally break basic functionality.

**Comment by rootulp** [comment]
Related: https://github.com/celestiaorg/celestia-core/issues/953
