### ISSUE TITLE
config: add `MaxGossipDelay` to the mempool config

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-core#957]
Ref

> I couldn't find a place where we are actually allowing for a different configured value here in the original PR or in CAT4, do we have a way to do that? If not, is that something we want to support? (also we could just create an issue to do this in the future, we don't have to add this here)

_Originally posted by @evan-forbes in https://github.com/celestiaorg/celestia-core/pull/943#discussion_r1091288011_

**Comment by evan-forbes** [comment]
@staheri14 mentioned in a grooming session that having a unit test to make sure that we are not disposing of wanted transactions if they surpass the timeout would be a good sanity check.

**Comment by evan-forbes** [comment]
closing as completed

**Comment by staheri14** [comment]
> mentioned in a grooming session that having a unit test to make sure that we are not disposing of wanted transactions if they surpass the timeout would be a good sanity check.


Has it been considered to add a unit test for this? [if there is none already]
